name: Build Jeton HiSilicon Luofu 22.03.6
on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        type: string
        required: true
        default: "22.03.6"
      openwrt_arch:
        description: "OpenWrt arch"
        type: string
        required: true
        default: "arm_cortex-a9"
      openwrt_target:
        description: "OpenWrt target"
        type: string
        required: true
        default: "hisilicon"
      openwrt_subtarget:
        description: "OpenWrt subtarget"
        type: string
        required: true
        default: "luofu"
      openwrt_vermagic:
        description: "OpenWrt vermagic"
        type: string
        required: true
        default: "da6486455e124a3f311d4af8607340d4"

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Info
      run: |
        echo "Building OpenWrt ${{ github.event.inputs.openwrt_version }}"
        echo "Target: ${{ github.event.inputs.openwrt_target }}/${{ github.event.inputs.openwrt_subtarget }}"
